---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dwca-config
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-ceph"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

