apiVersion: v1
data:
  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
    	<Appenders>
    		<Console name="CONSOLE">
    			<PatternLayout pattern="%d{HH:mm:ss.SSS}|%-5level|%c{10}: %msg%n" />
    		</Console>
    		<File name="FILE" fileName="/opt/jboss/wildfly/standalone/log/nba.log">
    			<PatternLayout pattern="%d{HH:mm:ss.SSS}|%-5level|%c{10}: %msg%n" />
    		</File>
    	</Appenders>
    	<Loggers>
    		<Logger name="nl.naturalis" level="INFO" additivity="false">
    			<AppenderRef ref="CONSOLE" />
    		</Logger>
    		<Root level="ERROR">
    			<AppenderRef ref="CONSOLE" />
    		</Root>
    	</Loggers>
    </Configuration>
  nba.properties: |+
    # Configuration file for the NBA. If you change these properties here,
    # you must also change these properties for the import programs
    # (in module nl.naturalis.nba.sh etl/conf/nba.properties)

    nba.api.install.dir=/etc/nba

    elasticsearch.cluster.name={{ elasticsearch_cluster_name}}
    elasticsearch.transportaddress.host=elasticsearch-discovery
    elasticsearch.transportaddress.port=9300

    elasticsearch.index.default.shards=12
    elasticsearch.index.default.replicas=2

    # Single index setup
    #elasticsearch.index.0.name=nba
    #elasticsearch.index.0.types=Specimen,Taxon,MultiMediaObject,GeoArea

    # Index-per-type setup
    elasticsearch.index.0.name=specimen
    elasticsearch.index.0.types=Specimen

    elasticsearch.index.1.name=taxon
    elasticsearch.index.1.types=Taxon

    elasticsearch.index.2.name=multimedia
    elasticsearch.index.2.types=MultiMediaObject

    elasticsearch.index.3.name=geoareas
    elasticsearch.index.3.types=GeoArea

    # The maximum number of buckets (unique scientific names) that
    # Elasticsearch must find. Elasticsearch will stop aggregating over the
    # result set the moment it has found this many buckets.
    nl.naturalis.nba.specimen.groupByScientificName.maxNumBuckets=10000

    # The maximum number of groups that Elasticsearch can collect when
    # aggregating a set of documents
    nl.naturalis.nba.aggregations.maxNumGroups=10000

    # The size of the query cache, which maps queries to their results.
    nl.naturalis.nba.specimen.groupByScientificName.queryCacheSize=1000
    # The number of milliseconds a query must at least take to be cached.
    nl.naturalis.nba.specimen.groupByScientificName.cacheTreshold=3000

    nl.naturalis.nba.taxon.groupByScientificName.maxNumBuckets=10000
    nl.naturalis.nba.taxon.groupByScientificName.queryCacheSize=1000
    nl.naturalis.nba.taxon.groupByScientificName.cacheTreshold=3000

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: etc-nba
