---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: field-metadata-config
  annotations:
    # volume.beta.kubernetes.io/storage-class: "nfs-ceph"
    volume.beta.kubernetes.io/storage-class: "example-nfs"
    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

