---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nba-purl-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "{{ purl_base_url }}"
    http:
      paths:
      - backend:
          serviceName: nba-purl
          servicePort: 8080

