apiVersion: v1
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
    	<Appenders>
    		<Console name="CONSOLE">
    			<PatternLayout pattern="%d{HH:mm:ss.SSS}|%-5level|%c{10}: %msg%n" />
    		</Console>
     	</Appenders>
    	<Loggers>
    		<Logger name="nl.naturalis" level="INFO" additivity="false">
    			<AppenderRef ref="CONSOLE" />
    		</Logger>
    		<Root level="ERROR">
    			<AppenderRef ref="CONSOLE" />
    		</Root>
    	</Loggers>
    </Configuration>
kind: ConfigMap
metadata:
  name: purl.log4j2.xml
