---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: p8s-elastic-exporter
  name: p8s-elastic-exporter
spec:
  ports:
    - name: http
      port: 9108
      protocol: TCP
      targetPort: 9108
  selector:
    app: p8s-elastic-exporter
  type: "ClusterIP"

