---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nba-landing
  labels:
    app: nba-landing
spec:
  replicas: {{ landing_replicas }}
  template:
    metadata:
      name: nba-landing
      labels:
        app: nba-landing
    spec:
      containers:
      - name: nba-entrypoint
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          httpGet:
            path: /
            port: 80
          failureThreshold: 10
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"
        image: {{ landing_docker_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80

